[project]
name = "idm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "openai-agents>=0.0.19",
    "prisma>=0.15.0",
]
